<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="drules" nsURI="http://org.eclipse.mylyn.reviews.r4e.core.model.drules.ecore/1.0"
    nsPrefix="org.eclipse.mylyn.reviews.r4e.core.model.drules.ecore">
  <eClassifiers xsi:type="ecore:EClass" name="R4EDesignRuleCollection" eSuperTypes="platform:/plugin/org.eclipse.mylyn.reviews.core/model/reviews.ecore#//ReviewComponent platform:/plugin/org.eclipse.mylyn.reviews.core/model/reviews.ecore#//ModelVersioning">
    <eStructuralFeatures xsi:type="ecore:EReference" name="areas" upperBound="-1"
        eType="#//R4EDesignRuleArea" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="folder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R4EDesignRule" eSuperTypes="platform:/plugin/org.eclipse.mylyn.reviews.core/model/reviews.ecore#//ReviewComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rank" eType="#//R4EDesignRuleRank"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="class" eType="#//R4EDesignRuleClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R4EDesignRuleArea" eSuperTypes="platform:/plugin/org.eclipse.mylyn.reviews.core/model/reviews.ecore#//ReviewComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="violations" upperBound="-1"
        eType="#//R4EDesignRuleViolation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="R4EDesignRuleViolation" eSuperTypes="platform:/plugin/org.eclipse.mylyn.reviews.core/model/reviews.ecore#//ReviewComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" upperBound="-1"
        eType="#//R4EDesignRule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="R4EDesignRuleRank">
    <eLiterals name="None" literal="NONE"/>
    <eLiterals name="Minor" literal="MINOR" value="1"/>
    <eLiterals name="Major" literal="MAJOR" value="2"/>
    <eLiterals name="Deprecated" literal="DEPRECATED" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="R4EDesignRuleClass">
    <eLiterals name="Erroneous" literal="ERRONEOUS"/>
    <eLiterals name="Superfluous" literal="SUPERFLUOUS" value="1"/>
    <eLiterals name="Improvement" literal="IMPROVEMENT" value="2"/>
    <eLiterals name="Question" literal="QUESTION" value="3"/>
    <eLiterals name="Comment" literal="COMMENT" value="4"/>
    <eLiterals name="Missing" literal="MISSING" value="5"/>
  </eClassifiers>
</ecore:EPackage>
